server: 
   servlet:
      session: 
         tracking-modes: cookie
   tomcat:
      uri-encoding: UTF-8
spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/oauth2_development
      username: oauth2
      password: oauth2
   mvc:
      view:
         prefix: /WEB-INF/jsp/
         suffix: .jsp
